# Setup
name:                InstaGallery
title:               InstaGallery
tagline:             A simple, easy to use Instagram gallery.
author:              BeeBack
author_email:        support@beeback.io
url:                 https://beeback.github.io/InstaGallery/
baseurl:             ''
permalink:           pretty
exclude:             [README.markdown]
analytics_id:

# Owner/author information
owner:
  name:           BeeBack
  avatar:         logo.png
  bio:            Loyalty service for SMB
  email:          sazzad@beeback.io
  twitter:        BeeBack
  github:         iamshipon1988
  instagram:      beebackapp
  location:       "New York, NY"


# Custom vars
version:             1.0.2
github:
  repo:
